### ISSUE TITLE
Not sure how to run

### ISSUE THREAD

**Issue by Darkness-to-LIGHT** [m2sup3rn0va/RASEv2#1]
Thanks for all the detailed work. I have never used python before so am struggling. I have managed to install everything as mentioned but how do I run in windows the python app. Where do I place, does it need to be loaded?

I seem to be missing something. I have tried putting the files in many locations, one such attempt says;

```
C:\Users\Owner\AppData\Local\Programs\Python\Python310>python RASEv2.py
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\RASEv2.py", line 6, in <module>
    from ui.ui_systray import UI_SystemTray
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\ui\ui_systray.py", line 6, in <module>
    from ui.ui_rootavd import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\ui\ui_rootavd.py", line 6, in <module>
    from bin.rootavd import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\bin\rootavd.py", line 7, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```
I have installed the python, install andriod studio, followed the instructions, install windows terminal, run the pip command, tried to run the RASEv2.py from a few locations.

Thanks, I am trying to build an emulator to support an rare app for study so it dosn't get lost.
With Thanks and Peace

**Comment by Darkness-to-LIGHT** [comment]
Quick update, it seems I didn't run all the comands earlier on, so I did it manualy;

pip install wget
pip install rich
pip install pyqt5 
pip install pyqt5-tools

cd C:\Users\Owner\AppData\Local\Programs\Python\Python310\  (I placed the files here)
python RASEv2.py

Program now open so I can test.

**Comment by Darkness-to-LIGHT** [comment]
Everything seems to work fine. I did notice the CSS in the pull down menu is dark, so I could not see all the ROMS listed, and thought something was wrong.

I am stuck on the burpsuite cert, how is this created if you don't mind?

Also at what point can I edit the rom, for the resolution and screen size.

Thanks

**Comment by Darkness-to-LIGHT** [comment]
Hi thanks, so I think I have everything working, the only question is about the Burp Cert, I see in your old version you state: 
`Asks user the name of the AVD to root, then roots it, installs Burp cert provided by the user in the Root CA Store and creates a rooted snapshot for rebooting`
Can you explain how I generate the required burb cert, also is it a one off, will it cause problems in the future. I am working with the V2. Also as mentioned, when can I edit the size of the emulated tablet (internal settings) in this sequence.
With thanks.

**Comment by Darkness-to-LIGHT** [comment]
Ok so I found https://portswigger.net/burp/communitydownload & https://github.com/alphaSeclab/awesome-burp-suite/blob/master/Readme_en.md though I don't know if burp is free, can this be made without a paid licence. Could you put my to instructions if so? With thanks.
